language: c
before_script:
  - chmod a+x ndk.sh
  - ./ndk.sh
  - export ANDROID_BUILD=yes
  - chmod a+x android-configure
  - ./android-configure
  - make configure
  - ./configure
  - export AR=/home/travis/build/geeteshk/git/android-toolchain/bin/arm-linux-androideabi-ar
  - export CC=/home/travis/build/geeteshk/git/android-toolchain/bin/arm-linux-androideabi-gcc
  - export CXX=/home/travis/build/geeteshk/git/android-toolchain/bin/arm-linux-androideabi-g++
  - export LINK=/home/travis/build/geeteshk/git/android-toolchain/bin/arm-linux-androideabi-g++
  - export CPPFLAGS="-fPIE"
  - export LDFLAGS="-fPIE -pie -L$PREFIX/lib"
  
script: 
  - make all
  
after_success:
  - file git
  - "curl -H \"Authorization: Bearer $ACCESS_TOKEN\" https://api-content.dropbox.com/1/files_put/auto/ -T /home/travis/build/geeteshk/git/git"
