language: c
before_script:
  - chmod a+x ndk.sh
  - ./ndk.sh
  - export ANDROID_BUILD=yes
  - chmod a+x android-configure
  - ./android-configure
  - make configure
  - ./configure
  
script: 
  - make
  - ls
  - ls out
  - echo $CC
